variables:
  dockerId: egorlukvinsky96  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: yadplayer  # Replace with the name of the image you want to publish

steps:
- task: Docker@2
  inputs:
    dockerfile: Dockerfile.web
  script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)

    docker login --username=_ --password=$(token) registry.heroku.com

    docker build -t registry.heroku.com/yadplayer/web .
    docker push registry.heroku.com/yadplayer/web
- task: Docker@2
  inputs:
    dockerfile: Dockerfile.worker
  script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)

    docker login --username=_ --password=$(token) registry.heroku.com

    docker build -t registry.heroku.com/yadplayer/worker .
    docker push registry.heroku.com/yadplayer/worker
