FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY WebApplication1/*.csproj ./WebApplication1/
COPY DomainLogic/*.csproj ./DomainLogic/
COPY Implementations/*.csproj ./Implementations/
COPY Implementations.Mq/*.csproj ./Implementations.Mq/
COPY Implementations.YandexDiskAPI/*.csproj ./Implementations.YandexDiskAPI/
COPY WorkerService/*.csproj ./WorkerService/
RUN dotnet restore

# copy everything else and build app
COPY WebApplication1/. ./WebApplication1/
COPY DomainLogic/. ./DomainLogic/
COPY Implementations/. ./Implementations/
COPY Implementations.Mq/. ./Implementations.Mq/
COPY Implementations.YandexDiskAPI/. ./Implementations.YandexDiskAPI/
COPY WorkerService/. ./WorkerService/

WORKDIR /app/WebApplication1
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/WebApplication1/out ./

CMD ASPNETCORE_URLS=http://*:$PORT dotnet WebApplication1.dll